server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    driver-class-name: org.postgresql.Driver
    username: demo
    password: demo

  jpa:
    show-sql: false