server:
  port: 0
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true
          use-services-query: true
          include-description: true
  application:
    name: as-app
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: demo
      password: demo
      schema: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    generate-ddl: false
  flyway:
    schemas: public
